### PR TITLE
added details about the bindings to the output

### PR DESCRIPTION
**Pull request by jpriebe**
Sample output:

```
ServiceAccount: default/test-user
Secrets:
• */test-user-token-mtmsz

Policies:
• [RB] default/test ⟶  [R] default/test-role
  Resource  Name  Exclude     Verbs      G L W C U P D DC         
  pods      [*]     [-]    [edit, exec]  ✔ ✖ ✖ ✖ ✖ ✖ ✖ ✖  

  Name      PRIV   RO-RootFS  Volumes  Caps  SELinux      RunAsUser      FSgroup   SUPgroup  
  test-psp  False    False      [*]    [*]   RunAsAny  MustRunAsNonRoot  RunAsAny  RunAsAny  

• [CRB] */test ⟶  [CR] */edit
  Resource                                     Name  Exclude      Verbs      G L W C U P D DC         
  bindings                                     [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  configmaps                                   [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  controllerrevisions.apps                     [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  cronjobs.batch                               [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  cronjobs.batch/status                        [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  daemonsets.apps                              [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  daemonsets.apps/status                       [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  daemonsets.extensions                        [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  daemonsets.extensions/status                 [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  deployments.apps                             [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  deployments.apps/rollback                    [*]     [-]         [-]       ✖ ✖ ✖ ✔ ✔ ✔ ✔ ✔  
  deployments.apps/scale                       [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  deployments.apps/status                      [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  deployments.extensions                       [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  deployments.extensions/rollback              [*]     [-]         [-]       ✖ ✖ ✖ ✔ ✔ ✔ ✔ ✔  
  deployments.extensions/scale                 [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  deployments.extensions/status                [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  endpoints                                    [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  events                                       [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  horizontalpodautoscalers.autoscaling         [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  horizontalpodautoscalers.autoscaling/status  [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  ingresses.extensions                         [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  ingresses.extensions/status                  [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  ingresses.networking.k8s.io                  [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  ingresses.networking.k8s.io/status           [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  jobs.batch                                   [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  jobs.batch/status                            [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  limitranges                                  [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  namespaces                                   [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  namespaces/status                            [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  networkpolicies.extensions                   [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  networkpolicies.networking.k8s.io            [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  persistentvolumeclaims                       [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  persistentvolumeclaims/status                [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  poddisruptionbudgets.policy                  [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  poddisruptionbudgets.policy/status           [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  pods                                         [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  pods/attach                                  [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  pods/exec                                    [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  pods/log                                     [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  pods/portforward                             [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  pods/proxy                                   [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  pods/status                                  [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  replicasets.apps                             [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicasets.apps/scale                       [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicasets.apps/status                      [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  replicasets.extensions                       [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicasets.extensions/scale                 [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicasets.extensions/status                [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  replicationcontrollers                       [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicationcontrollers.extensions/scale      [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicationcontrollers/scale                 [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  replicationcontrollers/status                [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  resourcequotas                               [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  resourcequotas/status                        [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  secrets                                      [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  serviceaccounts                              [*]     [-]    [impersonate]  ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  services                                     [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  services/proxy                               [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  services/status                              [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖  
  statefulsets.apps                            [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  statefulsets.apps/scale                      [*]     [-]         [-]       ✔ ✔ ✔ ✔ ✔ ✔ ✔ ✔  
  statefulsets.apps/status                     [*]     [-]         [-]       ✔ ✔ ✔ ✖ ✖ ✖ ✖ ✖ 
```

### CODE REVIEW

**Review by Ladicle — APPROVED** [review]
Thanks @jpriebe, it's easier to grasp the RBAC structure :)

**Comment by Ladicle** [comment]
ref: https://github.com/Ladicle/kubectl-rolesum/issues/26

**Comment by jpriebe** [comment]
Thanks, @Ladicle.  Glad you liked it.  One thing -- I'm not sure about the unicode arrow that I used ("LONG RIGHTWARDS ARROW").  The regular arrows were just too short -- they barely looked like arrows in my terminal.  But this one takes up the space of two characters.  I had to add a double space at the end, because it seems that some terminals render the double-wide character on top of the following character.  But it is not consistent -- so on some terminals, you might see two spaces after the arrow.

I thought about using something  like "-->", but you've done such a nice job with Unicode characters throughout the application, I didn't think a pure ASCII arrow would look right.

**Comment by jpriebe** [comment]
Are you planning a release in the near future?  Right now, I'm building the plugin for the team to take advantage of this PR, but I'd love to just point them to the releases.

**Comment by Ladicle** [comment]
I'm planning a release this weekend, so please wait a couple of days :)

**Comment by jpriebe** [comment]
Thanks for the release.  You might want to change out the screeshot, since the output is a little different now.  I would make you a new one, but I don't have the cute kitten picture for a background!  :-)

**Comment by Ladicle** [comment]
Oh, I forget to update :P Thank you for reminding me!

**Pull request merged**
